version: "3.3"
services:
    database:
        image: postgres:12.4
        container_name: indexes-app-db
        environment: 
            - POSTGRES_PASSWORD=docker
        ports: 
            - "5432:5432"
        volumes: 
            - ./dbdata:/var/lib/postgresql/data
            - ../src/database/database-schema.sql:/database-schema.sql
            - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
